config/routes.rb
Rails.application.routes.draw do
  # resources :movies, only: %w[index show]
  resources :lists, only: %w[index show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    bookmarks = Bookmark.where(list_id: params[:id])
    @movies = []
    bookmarks.each do |bookmark|
      @movies.push(Movie.find(bookmark.movie_id))
    end
  end

  def new
    @list = List.new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between p-3 h3">
  <div class="container">
  <i class="fa-solid fa-ticket"></i>
    <div class="form-inline my-2 my-lg-0">
      <%= link_to "My Lists", lists_path %>
      <%= link_to "New List", new_list_path %>
    </div>
  </div>
</nav>

<div class="container">
<h1 class="text-center mb-3">What List do you want to take a look into ?</h1>
<p>Find me in app/views/lists/index.html.erb</p>

<div class="row">
<% @lists.each do |list|%>
<div class="card"><%= link_to list.name, list_path(list) %></div>
<% end %>
</div>

</div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between p-3 h3">
  <div class="container">
    <i class="fa-solid fa-ticket"></i>
      <div class="form-inline my-2 my-lg-0">
        <%= link_to "My Lists", lists_path %>
        <%= link_to "New List", new_list_path %>
      </div>
  </div>
</nav>


<div class="container">
  <h1>Lists#show</h1>
  <p>Find me in app/views/lists/show.html.erb</p>

  <h2><%= @list.name %></h2>

  <ul>
    <% @movies.each do |movie|%>
      <li><%= link_to movie.title, movie_path(movie) %></li>
    <% end %>
  </ul>
</div>